{% set name = "pycbf" %}
{% set version = "0.9.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 56f1d5b67003ac1e7e96bf13fb4586160799ead41e520217cf18e9758e5decfe

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - cython
    - python
    - pip
    - poetry-core
  run:
    - python
    - numpy >=1.17

test:
  imports:
    - pycbf
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dials/pycbf
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENCE.txt
  summary: An API for CBF/imgCIF Crystallographic Binary Files
  description: |
    pycbf is a Python library for reading CBF formatted files.
  dev_url: https://github.com/dials/pycbf

extra:
  recipe-maintainers:
    - ndevenish
    - anthchirp
