{% set name = "pycbf" %}
{% set version = "0.9.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7fd23a79b40ec74cbc6829946ba6fe9eff6b4b3bda932e4ebce82a953299aeb4

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - cython
    - python
    - pip
    - poetry-core
  run:
    - python
    - numpy >=1.17

test:
  imports:
    - pycbf
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dials/pycbf
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENCE.txt
  summary: A Python API for reading CBF/imgCIF Crystallographic Binary Files, from Paul J Ellis and Herbert J Bernstein.
  description: |
    CBFlib is a library from from Paul J Ellis and Herbert J Bernstein for
    reading CBF/imgCIF crystallographic binary files. This is the python
    parts of that library, split off and built separately.
  dev_url: https://github.com/dials/pycbf
  doc_url: http://www.bernstein-plus-sons.com/software/CBF/doc/CBFlib.html

extra:
  recipe-maintainers:
    - rjgildea
    - ndevenish
    - anthchirp
