{% set name = "pycbf" %}
{% set version = "0.9.6.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 981bc5d537e4dd578ab5f3d579042676c9f9abe24609b96aca59f8933a75b4e6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - setuptools
  host:
    - cython
    - pip
    - python
  run:
    - numpy >=1.17
    - python

test:
  imports:
    - pycbf
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dials/pycbf
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENCE.txt
  summary: A Python API for reading CBF/imgCIF Crystallographic Binary Files, from Paul J Ellis and Herbert J Bernstein.
  description: |
    CBFlib is a library from from Paul J Ellis and Herbert J Bernstein for
    reading CBF/imgCIF crystallographic binary files. This is the python
    parts of that library, split off and built separately.
  dev_url: https://github.com/dials/pycbf
  doc_url: http://www.bernstein-plus-sons.com/software/CBF/doc/CBFlib.html

extra:
  recipe-maintainers:
    - rjgildea
    - ndevenish
    - anthchirp
